[package]
name = "yomuyume"
version = "1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "yomuyume"
path = "src-rust/main.rs"

[dependencies]
argon2 = "0.5.2"
axum = "0.7.2"
axum-extra = { version = "0.9.0", features = ["cookie"] }
axum-macros = "0.4.0"
blurhash = "0.2.3"
chrono = { version = "0.4.30", features = ["serde"] }
dotenvy = "0.15.7"
email_address = "0.2.4"
http-serde = "2.0.0"
image = { version = "0.25.2", features = ["avif-native"] }
lettre = "0.11.2"
notify = "6.1.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
semver = { version = "1.0.18", features = ["serde"] }
serde = { version = "1.0.188", features = ["serde_derive"] }
serde_json = "1.0.108"
tokio = { version = "1.32.0", features = ["full"] }
tower-http = { version = "0.5.0", features = ["tracing", "trace", "cors"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
utoipa = { version = "4.1.0", features = ["axum_extras", "chrono", "uuid"] }
utoipa-redoc = { version = "4.0.0", features = ["axum"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["axum"] }
anyhow = "1.0.89"
memfd-exec = "0.2.1"
quick-xml = { version = "0.36.2", features = ["async-tokio", "serde", "tokio", "serialize"] }
sqlx = { version = "0.8.2", features = ["runtime-tokio", "postgres", "chrono"] }
snowflake = { git = "https://github.com/Liminova/snowflake-rs", version = "1.0.0" }
num_cpus = "1.16.0"
async-channel = "2.3.1"

[dev-dependencies]
axum-test = "14.0.0"
tempdir = "0.3.7"
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
nanoid = "0.4.0"

[profile.dev.package.sqlx-macros]
opt-level = 3

[[bench]]
name = "main"
harness = false
