services:
    postgres:
        image: postgres:17-alpine
        restart: unless-stopped
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: yomuyume
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: unless-stopped
        volumes:
            - pgadmin:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - 5433:80
        depends_on:
            - postgres

volumes:
    pgdata:
    pgadmin: