[package]
name = "blurhash-decode"
version = "0.1.0"
authors = ["Delnegend <kiennguyen19323@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
console_error_panic_hook = "0.1.7"
image = { version = "0.25.2", features = ["webp"], default-features = false }
wasm-bindgen = "0.2.84"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
