services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        tty: true
        user: 1000:1000
        volumes:
            - ../:/ymym
            - cargo-cache:/usr/local/cargo
            - global-pnpm-store:/home/ymym/.pnpm-store
        deploy:
            resources:
                limits:
                    memory: 8g
        environment:
            LISTEN_ADDRESS: 0.0.0.0:3000

            LIBRARY_PATH: /ymym/library
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ymym
            # REVERSE_PROXY_IP_HEADER: CF-Connecting-IP # the header containing real ip address if you're behind a reverse proxy

            FEATURE_NOMEDIA: 'false'
            FEATURE_KOMGA_ONESHOT: 'false'
            FEATURE_KOMGA_RECYCLE: 'false'

            RESCAN_INTERVAL_SECS: '21600' # 6 hours
            RESCAN_THREAD: '8'

            SMTP_HOST: smtp.example.com
            SMTP_USERNAME: user@example.com
            SMTP_PASSWORD: password
            SMTP_FROM_EMAIL: from@example.com
            SMTP_FROM_NAME: Yomuyume

volumes:
    cargo-cache:
    global-pnpm-store:
