[package]
name = "yomuyume"
version = "1.0.3"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "yomuyume"
path = "main.rs"

[dependencies]
anyhow = "1.0.89"
api-endpoints = { path = "../api-endpoints" }
argon2 = "0.5.3"
async-channel = "2.3.1"
axum = "0.8.1"
axum-extra = { version = "0.10.0", features = ["cookie", "query"] }
axum-macros = "0.5.0"
blurhash = "0.2.3"
chrono = { version = "0.4.30", features = ["serde"] }
dashmap = { version = "6.1.0", features = ["inline"] }
dotenvy = "0.15.7"
email_address = "0.2.4"
futures-core = "0.3.31"
futures-util = "0.3.31"
http-serde = "2.0.0"
image = { version = "0.25.2", features = ["avif-native"] }
jxl-oxide = { version = "0.11.0", features = ["image"] }
lettre = "0.11.2"
memfd-exec = "0.2.1"
quick-xml = { version = "0.37.2", features = [
    "async-tokio",
    "serde",
    "tokio",
    "serialize",
] }
semver = { version = "1.0.18", features = ["serde"] }
serde = { version = "1.0.188", features = ["serde_derive"] }
serde_json = "1.0.108"
serde_with = "3.12.0"
snowflake = { git = "https://github.com/Liminova/snowflake-rs", version = "1.0.0" }
sqlx = { version = "0.8.2", features = ["runtime-tokio", "postgres", "chrono"] }
frontend-spa = { path = "../frontend-spa" }
thiserror = "2.0.2"
tokio = { version = "1.32.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["io"] }
tower-http = { version = "0.6.2", features = ["tracing", "trace", "cors"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "ansi"] }
utoipa = { version = "5.3.1", features = ["axum_extras", "chrono"] }
utoipa-redoc = { version = "6.0.0", features = ["axum"] }

[dev-dependencies]
axum-test = "17.1.0"
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
nanoid = "0.4.0"
regex = "1.11.1"
tempfile = "3.14.0"
tracing-test = "0.2.5"

[build-dependencies]

[[bench]]
name = "main"
harness = false
path = "benches/main.rs"
