[package]
name = "yomuyume"
version = "1.0.3"
edition = "2024"

[[bin]]
name = "yomuyume"
path = "main.rs"

[dependencies]
api-endpoints = { path = "../api-endpoints" }
argon2 = "0.5.3"
axum = "0.8.4"
axum-extra = { version = "0.10.1", features = ["cookie", "query"] }
chrono = { version = "0.4.42", features = ["serde"] }
frontend-spa = { path = "../frontend-spa" }
image = { version = "0.25.8", features = ["avif-native"] }
lettre = "0.11.18"
quick-xml = { version = "0.38.3", features = ["serialize", "encoding"] }
rayon = "1.11.0"
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.143"
serde_with = "3.14.0"
sqlx = { version = "0.8.6", features = [
    "sqlite",
    "chrono",
    "runtime-tokio",
    "sqlx-macros",
] }
tantivy = "0.25.0"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = { version = "0.7.16", features = ["io"] }
tower-http = { version = "0.6.6", features = ["tracing", "trace", "cors"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "ansi"] }
utoipa = { version = "5.4.0", features = ["axum_extras", "chrono"] }
utoipa-redoc = { version = "6.0.0", features = ["axum"] }

[dev-dependencies]
anyhow = "1.0.99"
criterion = { version = "0.7.0", features = ["html_reports", "async_tokio"] }
regex = "1.11.1"
tempfile = "3.14.0"
tracing-test = "0.2.5"


[[bench]]
name = "main"
harness = false
path = "benches/main.rs"
